DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE CLIENT (
    cli1 INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    registerDate DATE NOT NULL,
    image BLOB,
    totalSalary FLOAT
);

CREATE TABLE ACCOUNT (
    acc1 INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    balance FLOAT NOT NULL,
    openDate DATE NOT NULL,
    cli1 INT NOT NULL,
    FOREIGN KEY (cli1) REFERENCES Client(cli1)
);